version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql


  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    env_file:
      - .env
    environment:
      PSQL_HOST: postgres
    ports:
      - '3001:3000'

volumes:
  pg_data:
