version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql


  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      POSTGRES_HOST: postgres
      JWT_ACCESS_SECRET: secret
      JWT_ACCESS_EXPIRES: 15m
    ports:
      - '3001:3000'

volumes:
  pg_data:
